name = "cloudflare-remix-prisma"
type = "javascript"
workers_dev = true
compatibility_date = "2021-12-08"
# account_id = "Or specified with process.env.CF_ACCOUNT_ID"
# zone_id = "Or specified with process.env.CF_ZONE_ID"
# route = "example.com/*"
kv_namespaces = [
  {binding = "REDIRECTS", id = "8611acfb88ad4ed0b6ef07471e2bb700"},
]

[site]
bucket = "./public"
entry-point = "."

[build]
command = "yarn build"
watch_dir = "app"

[build.upload]
format = "service-worker"
