name = "cloudflare-remix-prisma"
type = "javascript"
workers_dev = true
# account_id = "Or specified with process.env.CF_ACCOUNT_ID"
# zone_id = "Or specified with process.env.CF_ZONE_ID"
# route = "example.com/*"
kv_namespaces = [
  {binding = "REDIRECTS", id = "353f273a717a8628a36b9f6ecaa49f07"},
]

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"
watch_dir = "app"

[build.upload]
format = "service-worker"
